### ISSUE TITLE
Deprecated packages

### ISSUE THREAD

**Issue by dbrattli** [fable-compiler/packages#4]
Deprecated packages seems to be listed without any warning. E.g for https://fable.io/packages/#/package/fable-py all packages are deprecated. It might be time to delete or unlist, but there should probably be a warning when showing such packages.

**Comment by MangelMaxime** [comment]
@dbrattli NuGet still list the packages in the search result because a package is never deleted from the server.

Changes that we can do:
- Add a warning in the "Package Home" if the viewed version is unlisted.
- In the versions tab, list all the available version for a package but add a warning Icon if that specific version is unlisted.

**Comment by MangelMaxime** [comment]
Did you add something special to the `fable-py` metadata to get the `Fable` suggestion? Or is this something automatic from NuGet?

![image](https://user-images.githubusercontent.com/4760796/194822739-f0182f51-212a-4ae5-a88f-cc9f033b7e03.png)

**Comment by dbrattli** [comment]
Yes, when you deprecate a package you can select an alternative:

![image](https://user-images.githubusercontent.com/849479/194834106-e4a9bf1d-b51c-4856-af57-6223e705494f.png)

**Comment by MangelMaxime** [comment]
Hum, I will have a look if that "alternate package" information is exposed from the API

**Comment by MangelMaxime** [comment]
@dbrattli A new version of Fable.Packages is available which add support for deprecated packages. The information is present at 2 different places.

In the package home header:

<img width="954" alt="image" src="https://user-images.githubusercontent.com/4760796/197347907-d00de066-8c4d-4cce-a146-255222b1f94d.png">


In versions list:

<img width="628" alt="image" src="https://user-images.githubusercontent.com/4760796/197347886-64088ef9-9bdd-48c4-a785-c5868af447d4.png">

**Comment by dbrattli** [comment]
Fantastic, this looks really nice. Great work! @MangelMaxime

**Comment by MangelMaxime** [comment]
Thank you :)

*Note for the future*

Not all the different reasons for deprecation have nice messages.

This is because the `deprecation` property is not documented in the NuGet API or I could not find it.

But they, will at minima display a generic deprecation message with an incentive to create an issue for that specific deprecation reason.

https://github.com/fable-compiler/packages/blob/5ef9f021fff46bd4056d110d02f7ca28e76760e8/src/Components/PackageHome/DeprecationWarning.fs#L48-L65
